Repository Loathing-Associates-Scripting-Society/philter, pull requests merged in 2020-12, with the labels that each got.

#2 Show Closet\Storage\Display amounts on relay page
  relay/relay_OCD_dB_Manager.ash
Labels: enhancement

#3 Move files into /release/, add README
  README.md
  release/data/OCDefault.txt
  release/data/OCDkBay.txt
  release/data/OCDstock.txt
  release/dependencies.txt
  release/relay/relay_OCD_dB_Manager.ash
  release/scripts/OCD Inventory Control.ash
Labels: type: documentation, type: enhancement

#4 Extract CSS and JS into separate files
  release/relay/ocd-db-manager/ocd-db-manager.web.js
  release/relay/ocd-db-manager/styles.css
  release/relay/relay_OCD_dB_Manager.ash
  release/scripts/OCD Inventory Control.ash
Labels: type: enhancement

#5 feat: Use alternating table row bgcolor
  release/relay/ocd-db-manager/styles.css
  release/relay/relay_OCD_dB_Manager.ash
Labels: type: enhancement

#8 Fix self-upgrading code, add upgrade instructions
  README.md
  release/scripts/OCD Inventory Control.ash
Labels: type: bug, type: documentation

#9 Rename project to OCD-Cleanup
  README.md
  release/data/ocd-cleanup-default.txt
  release/data/ocd-cleanup-kbay.txt
  release/data/ocd-cleanup-stock.txt
  release/relay/ocd-cleanup-manager/ocd-cleanup-manager.web.js
  release/relay/ocd-cleanup-manager/styles.css
  release/relay/relay_OCD-Cleanup_Manager.ash
  release/scripts/ocd-cleanup.ash
Labels: type: enhancement
